// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr4L2G0xZqGvtfy6KWAPvK_AIjynBPt_g',
    appId: '1:157494133593:web:8c7ceb49f1c9273a5e0248',
    messagingSenderId: '157494133593',
    projectId: 'talk-2-partners',
    authDomain: 'talk-2-partners.firebaseapp.com',
    storageBucket: 'talk-2-partners.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAwfJ5SIPLA46M7tNSyGKfww5Oo7hyVcw',
    appId: '1:157494133593:android:59fb4faa14a75d7d5e0248',
    messagingSenderId: '157494133593',
    projectId: 'talk-2-partners',
    storageBucket: 'talk-2-partners.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGl_fAZJFG97kELqdoqnp_0ZXnGGZMJA4',
    appId: '1:157494133593:ios:f7027bce77df7b435e0248',
    messagingSenderId: '157494133593',
    projectId: 'talk-2-partners',
    storageBucket: 'talk-2-partners.firebasestorage.app',
    iosBundleId: 'com.example.talk2partners',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGl_fAZJFG97kELqdoqnp_0ZXnGGZMJA4',
    appId: '1:157494133593:ios:f7027bce77df7b435e0248',
    messagingSenderId: '157494133593',
    projectId: 'talk-2-partners',
    storageBucket: 'talk-2-partners.firebasestorage.app',
    iosBundleId: 'com.example.talk2partners',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr4L2G0xZqGvtfy6KWAPvK_AIjynBPt_g',
    appId: '1:157494133593:web:68b1dfbf9fe49e345e0248',
    messagingSenderId: '157494133593',
    projectId: 'talk-2-partners',
    authDomain: 'talk-2-partners.firebaseapp.com',
    storageBucket: 'talk-2-partners.firebasestorage.app',
  );
}

